import { TaskWithRelations, TaskStatus } from '@/types/task';

export const mockTasks: TaskWithRelations[] = [
  {
    id: '1',
    title: 'Inventário Setor A',
    description: 'Realizar contagem completa de todos os itens do setor A',
    responsible_id: 'u-joao',
    requester_id: 'u-sup',
    status: 'em_andamento',
    priority: 'alta',
    category: 'almoxarifado_inventario',
    due_date: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    completed_at: null,
    approved_at: null,
    approved_by: null,
    rejection_reason: null,
    help_requested: false,
    help_reason: null,
    reopen_requested: false,
    reopen_reason: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    responsible: {
      id: 'u-joao',
      full_name: 'João Silva',
      email: 'joao.silva@vortice.com',
      role: 'almoxarife',
      avatar_url: null,
    },
    requester: {
      id: 'u-sup',
      full_name: 'Maria Santos',
      email: 'maria.santos@vortice.com',
      role: 'supervisor',
      avatar_url: null,
    },
    checklist_items: [
      {
        id: '1',
        task_id: '1',
        title: 'Contar itens críticos',
        completed: true,
        position: 0,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: '2',
        task_id: '1',
        title: 'Registrar divergências',
        completed: false,
        position: 1,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: '3',
        task_id: '1',
        title: 'Gerar relatório final',
        completed: false,
        position: 2,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
    ],
    comments_count: 2,
    attachments_count: 1,
  },
  {
    id: '2',
    title: 'Cotação Fornecedor XYZ',
    description: 'Solicitar cotação de materiais elétricos',
    responsible_id: 'u-carlos',
    requester_id: 'u-sup',
    status: 'a_fazer',
    priority: 'media',
    category: 'compras_cotacao',
    due_date: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    completed_at: null,
    approved_at: null,
    approved_by: null,
    rejection_reason: null,
    help_requested: false,
    help_reason: null,
    reopen_requested: false,
    reopen_reason: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    responsible: {
      id: 'u-carlos',
      full_name: 'Carlos Oliveira',
      email: 'carlos.oliveira@vortice.com',
      role: 'comprador',
      avatar_url: null,
    },
    requester: {
      id: 'u-sup',
      full_name: 'Maria Santos',
      email: 'maria.santos@vortice.com',
      role: 'supervisor',
      avatar_url: null,
    },
    checklist_items: [],
    comments_count: 0,
    attachments_count: 0,
  },
  {
    id: '3',
    title: 'Relatório Mensal de Indicadores',
    description: 'Compilar indicadores de desempenho do mês anterior',
    responsible_id: 'u-ana',
    requester_id: 'u-sup',
    status: 'aguardando_aprovacao',
    priority: 'baixa',
    category: 'administrativo_indicadores',
    due_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    completed_at: new Date().toISOString(),
    approved_at: null,
    approved_by: null,
    rejection_reason: null,
    help_requested: false,
    help_reason: null,
    reopen_requested: false,
    reopen_reason: null,
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    responsible: {
      id: 'u-ana',
      full_name: 'Ana Costa',
      email: 'ana.costa@vortice.com',
      role: 'assistente_administrativo',
      avatar_url: null,
    },
    requester: {
      id: 'u-sup',
      full_name: 'Maria Santos',
      email: 'maria.santos@vortice.com',
      role: 'supervisor',
      avatar_url: null,
    },
    checklist_items: [],
    comments_count: 1,
    attachments_count: 2,
  },
  {
    id: '4',
    title: 'Ajuste de Saldo - Material ABC',
    description: 'Corrigir saldo do material ABC123 após divergência encontrada',
    responsible_id: 'u-joao',
    requester_id: 'u-sup',
    status: 'concluido',
    priority: 'critica',
    category: 'almoxarifado_ajustes_saldo',
    due_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    completed_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    approved_at: new Date().toISOString(),
    approved_by: '2',
    rejection_reason: null,
    help_requested: false,
    help_reason: null,
    reopen_requested: false,
    reopen_reason: null,
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    responsible: {
      id: 'u-joao',
      full_name: 'João Silva',
      email: 'joao.silva@vortice.com',
      role: 'almoxarife',
      avatar_url: null,
    },
    requester: {
      id: 'u-sup',
      full_name: 'Maria Santos',
      email: 'maria.santos@vortice.com',
      role: 'supervisor',
      avatar_url: null,
    },
    checklist_items: [],
    comments_count: 3,
    attachments_count: 1,
  },
  {
    id: '5',
    title: 'Pedido de Compra #1234',
    description: 'Emitir pedido de compra para materiais de limpeza',
    responsible_id: 'u-carlos',
    requester_id: 'u-sup',
    status: 'aguardando_terceiros',
    priority: 'media',
    category: 'compras_pedido',
    due_date: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    completed_at: null,
    approved_at: null,
    approved_by: null,
    rejection_reason: null,
    help_requested: true,
    help_reason: 'Fornecedor não responde há 3 dias',
    reopen_requested: false,
    reopen_reason: null,
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    responsible: {
      id: 'u-carlos',
      full_name: 'Carlos Oliveira',
      email: 'carlos.oliveira@vortice.com',
      role: 'comprador',
      avatar_url: null,
    },
    requester: {
      id: 'u-sup',
      full_name: 'Maria Santos',
      email: 'maria.santos@vortice.com',
      role: 'supervisor',
      avatar_url: null,
    },
    checklist_items: [],
    comments_count: 5,
    attachments_count: 0,
  },
  {
    id: '6',
    title: 'Organização Física - Setor B',
    description: 'Reorganizar prateleiras e identificar localizações',
    responsible_id: 'u-joao',
    requester_id: 'u-sup',
    status: 'backlog',
    priority: 'baixa',
    category: 'almoxarifado_organizacao',
    due_date: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString(),
    completed_at: null,
    approved_at: null,
    approved_by: null,
    rejection_reason: null,
    help_requested: false,
    help_reason: null,
    reopen_requested: false,
    reopen_reason: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    responsible: {
      id: 'u-joao',
      full_name: 'João Silva',
      email: 'joao.silva@vortice.com',
      role: 'almoxarife',
      avatar_url: null,
    },
    requester: {
      id: 'u-sup',
      full_name: 'Maria Santos',
      email: 'maria.santos@vortice.com',
      role: 'supervisor',
      avatar_url: null,
    },
    checklist_items: [],
    comments_count: 0,
    attachments_count: 0,
  },
];

export function getTasksByStatus(status: TaskStatus): TaskWithRelations[] {
  return mockTasks.filter((task) => task.status === status);
}
